### ISSUE TITLE
Laser pecker API.   Any news ???

### ISSUE THREAD

**Issue by SimonGAndrews** [yy502/laserpecker#1]
Hello yy502,
Thanks for the review and work on the gcode extension, it's  very useful. 

Have you heard any news if the manufacturer is working on releasing an api or anything which would support controlling the laser remotely ??

I would be very interested to use it as a laser printer running off a raspberry pi.  Even basic functions to trigger print of a given stored image would be useful. 

Thanks, Simon 

PS

**Comment by yy502** [comment]
Hi Simon,

Thanks for your message.

I've been asking for an API for ages, but they are not releasing it, for now at least. Mainly it's because unlike 3D printers that take Gcode directly, LP engravers rely on the external application to convert images/G-codes to encrypted machine instructions and send to the engravers. The good news is that they are developing a cross-platform desktop client, and I'm hoping to be able to control the engraver via cmdline :-)

Yi

**Comment by SimonGAndrews** [comment]
Thanks Yi for the response.   Sounds like a good start,....  I will follow closely. Keep up the good work. :)
